services:
  - type: web
    name: efootkings-2026
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: efootkings-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

